DROP TABLE IF EXISTS Usuarios;
CREATE TABLE Usuarios (
    ID         VARCHAR UNIQUE NOT NULL,
    NOME       VARCHAR NOT NULL,
    CPF        VARCHAR,
    TELEFONE   VARCHAR,
    EMAIL      VARCHAR NOT NULL,
    PASSWORD   VARCHAR NOT NULL,
    CIDADE     VARCHAR NOT NULL,
    COD_CIDADE INTEGER NOT NULL,
    ESTADO     VARCHAR NOT NULL,
    COD_ESTADO INTEGER NOT NULL,
    INIT       BOOLEAN DEFAULT (0),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS FazTransporte;
CREATE TABLE FazTransporte (
    ID_USUARIO         VARCHAR NOT NULL,
    COD_CIDADE_ORIGEM  INTEGER NOT NULL,
    COD_CIDADE_DESTINO INTEGER NOT NULL,
    CIDADE_ORIGEM      VARCHAR,
    CIDADE_DESTINO     VARCHAR,
    COD_ESTADO_ORIGEM  INTEGER,
    ESTADO_ORIGEM      VARCHAR,
    COD_ESTADO_DESTINO INTEGER,
    ESTADO_DESTINO     VARCHAR,

    PRIMARY KEY ( ID_USUARIO, COD_CIDADE_ORIGEM, COD_CIDADE_DESTINO )
);

DROP TABLE IF EXISTS Municipios;
CREATE TABLE Municipios (
    ID_USUARIO         VARCHAR NOT NULL,
    COD_CIDADE         INTEGER NOT NULL,
    TEM_RODOVIARIO     BOOLEAN DEFAULT (0),
    TEM_AQUAVIARIO     BOOLEAN DEFAULT (0),
    TEM_BICICLETA      BOOLEAN DEFAULT (0),
    TEM_MONITOR        BOOLEAN DEFAULT (0),
    TEM_OUTRAS_CIDADES BOOLEAN DEFAULT (0),
    DIST_MINIMA        REAL,
    PRIMARY KEY ( ID_USUARIO, COD_CIDADE ),
    FOREIGN KEY ( ID_USUARIO ) REFERENCES Usuarios ( ID )
);

DROP TABLE IF EXISTS Aluno;
CREATE TABLE "Aluno" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"LATITUDE"	REAL NOT NULL,
	"LONGITUDE"	REAL NOT NULL,
	"ENDERECO"	TEXT,
	"CEP"	INTEGER,
	"DA_PORTEIRA"	BOOLEAN DEFAULT (0),
	"DA_MATABURRO"	BOOLEAN DEFAULT (0),
	"DA_COLCHETE"	BOOLEAN DEFAULT (0),
	"DA_ATOLEIRO"	BOOLEAN DEFAULT (0),
	"DA_PONTERUSTICA"	BOOLEAN DEFAULT (0),
	"NOME"	TEXT NOT NULL,
	"DATA_NASCIMENTO"	TEXT NOT NULL,
	"SEXO"	INTEGER NOT NULL,
	"COR"	INTEGER NOT NULL,
	"NOME_RESPONSAVEL"	TEXT NOT NULL,
	"GRAU_RESPONSAVEL"	INTEGER NOT NULL,
	"TELEFONE RESPONSÁVEL"	INTEGER,
	"DEF_CAMINHAR"	BOOLEAN DEFAULT (0),
	"DEF_OUVIR"	BOOLEAN DEFAULT (0),
	"DEF_ENXERGAR"	BOOLEAN DEFAULT (0),
	"DEF_MENTAL"	BOOLEAN DEFAULT (0),
	"ID_ESCOLA"	INTEGER NOT NULL,
	"TURNO"	INTEGER NOT NULL,
	"NIVEL"	INTEGER NOT NULL,
	FOREIGN KEY("ID_ESCOLA") REFERENCES "Escolas"("ID_ESCOLA")
);

DROP TABLE IF EXISTS Motorista;
CREATE TABLE "Motorista" (
	"ID_MOTORISTA"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"LATITUDE"	REAL NOT NULL,
	"LONGITUDE"	REAL NOT NULL,
	"NOME"	TEXT NOT NULL,
	"DATA_NASCIMENTO"	TEXT NOT NULL,
	"SEXO"	INTEGER NOT NULL,
	"NACIONALIDADE"	INTEGER,
	"DOC_IDENTIFICACAO"	INTEGER NOT NULL,
	"ORGAO_EMISSOR"	TEXT,
	"CPF"	INTEGER,
	"COR"	INTEGER NOT NULL,
	"DEF_CAMINHAR"	BOOLEAN DEFAULT (0),
	"DEF_OUVIR"	BOOLEAN DEFAULT (0),
	"DEF_ENXERGAR"	BOOLEAN DEFAULT (0),
	"DEF_MENTAL"	BOOLEAN DEFAULT (0),
    "AT_CRIMINAL" BLOB,
);


DROP TABLE IF EXISTS Garagem;
CREATE TABLE "Garagem" (
	"ID_GARAGEM"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"LATITUDE"	REAL NOT NULL,
	"LONGITUDE"	REAL NOT NULL,
	"ENDERECO"	TEXT,
	"CEP"	INTEGER
);

DROP TABLE IF EXISTS Veiculo;
CREATE TABLE "Veiculo" (
	"ID_VEICULO"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"PLACA"	INTEGER NOT NULL,
	"MODELO"	TEXT NOT NULL,
	"ANO"	INTEGER NOT NULL,
	"TIPO_TRANSPORTE"	BOOLEAN DEFAULT (0),
    "ORIGEM" INTEGER NOT NULL,
    "AQUISICAO" INTEGER,
	"POSSUI_GARAGEM" BOOLEAN DEFAULT (0),
    "KM_VEICULO" INTEGER,
    "ULTIMA_MANUTENCAO" TEXT,
    "CAPACIDADE_MAX" INTEGER NOT NULL,
    "CAPACIDADE_ATUAL" INTEGER
);

DROP TABLE IF EXISTS GaragemTemVeiculo;
CREATE TABLE "GaragemTemVeiculo" (
    "ID_VEICULO" INTEGER NOT NULL,
    "ID_GARAGEM" INTEGER NOT NULL,
    FOREIGN KEY("ID_VEICULO") REFERENCES "Veiculo"("ID_VEICULO"),
    FOREIGN KEY("ID_GARAGEM") REFERENCES "Garagem"("ID_GARAGEM"),
    PRIMARY KEY ("ID_VEICULO", "ID_GARAGEM")
);

DROP TABLE IF EXISTS EscolaTemAlunos;
CREATE TABLE "EscolaTemAlunos" (
	"ID_ESCOLA"	INTEGER NOT NULL,
	"ID_ALUNO"	INTEGER NOT NULL,
    FOREIGN KEY("ID_ESCOLA") REFERENCES "Escolas"("ID_ESCOLA"),
    FOREIGN KEY("ID_ALUNO") REFERENCES "Aluno"("ID_ALUNO"),
    PRIMARY KEY ("ID_ESCOLA", "ID_ALUNO")
);

DROP TABLE IF EXISTS Rota;
CREATE TABLE "Rota" (
    "ID_ROTA" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "KM" INTEGER,
    "FAZ_MATUTINO" BOOLEAN DEFAULT (0),
    "FAZ_VESPERTINO" BOOLEAN DEFAULT (0),
    "FAZ_NOTURNO" BOOLEAN DEFAULT (0),
    "COMECA_GARAGEM" BOOLEAN DEFAULT (0),
    "IDA_VOLTA" BOOLEAN DEFAULT (0),
    "HORA_INICIO" TEXT,
    "HORA_TERMINO" TEXT,
    "TEM_PONTO_PARADA" BOOLEAN DEFAULT (0),
    "TRACADO" TEXT
);

DROP TABLE IF EXISTS PontoParada;
CREATE TABLE PontoParada (
    "ID_PONTOPARADA" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "LATITUDE" REAL NOT NULL,
    "LONGITUDE" REAL NOT NULL,
    "TEM_INFRAESTRUTURA" BOOLEAN DEFAULT (0),
    "HORARIO_IDA" TEXT,
    "HORARIO_VOLTA" TEXT
);

DROP TABLE IF EXISTS RotaTemPontoParada;
CREATE TABLE RotaTemPontoParada (
    "ID_ROTA" NOT NULL,
    "ID_PONTOPARADA" NOT NULL,
    FOREIGN KEY("ID_ROTA") REFERENCES "Rota"("ID_ROTA"),
    FOREIGN KEY("ID_PONTOPARADA") REFERENCES "PontoParada"("ID_PONTOPARADA"),
    PRIMARY KEY ("ID_ROTA", "ID_PONTOPARADA")
);

DROP TABLE IF EXISTS AlunoUsaPontoParada;
CREATE TABLE AlunoUsaPontoParada (
    "ID_ALUNO" NOT NULL,
    "ID_PONTOPARADA" NOT NULL,
    FOREIGN KEY("ID_ALUNO") REFERENCES "Aluno"("ID_ALUNO"),
    FOREIGN KEY("ID_PONTOPARADA") REFERENCES "PontoParada"("ID_PONTOPARADA"),
    PRIMARY KEY ("ID_ALUNO", "ID_PONTOPARADA")
);

DROP TABLE IF EXISTS RotaTemMotorista;
CREATE TABLE "RotaTemMotorista" (
    "ID_ROTA" INTEGER NOT NULL,
    "ID_MOTORISTA" INTEGER NOT NULL,
    FOREIGN KEY("ID_ROTA") REFERENCES "Rota"("ID_ROTA"),
    FOREIGN KEY("ID_MOTORISTA") REFERENCES "Motorista"("ID_MOTORISTA"),
    PRIMARY KEY ("ID_ROTA", "ID_MOTORISTA")
);

DROP TABLE IF EXISTS RotaPassaPorEscola;
CREATE TABLE RotaPassaPorEscola (
    "ID_ROTA" INTEGER NOT NULL,
    "ID_ESCOLA" INTEGER NOT NULL,
    FOREIGN KEY("ID_ROTA") REFERENCES "Rota"("ID_ROTA"),
    FOREIGN KEY("ID_ESCOLA") REFERENCES "Escolas"("ID_ESCOLA"),
    PRIMARY KEY ("ID_ROTA", "ID_ESCOLA")
);

DROP TABLE IF EXISTS RotaPegaAluno;
CREATE TABLE RotaPegaAluno (
    "ID_ROTA" INTEGER NOT NULL,
    "ID_ESCOLA" INTEGER NOT NULL,
    FOREIGN KEY("ID_ROTA") REFERENCES "Rota"("ID_ROTA"),
    FOREIGN KEY("ID_ESCOLA") REFERENCES "Escolas"("ID_ESCOLA"),
    PRIMARY KEY ("ID_ROTA", "ID_ESCOLA")
);